app/models.py
from . import db
from werkzeug.security import generate_password_hash,check_password_hash
from flask_login import UserMixin
from . import login_manager
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))

class Pitches(db.Model):
    __tablename__= 'pitches'
    id = db.Column(db.Integer,primary_key = True)
    title = db.Column(db.String(255))
    category = db.Column(db.String(255))
    pitch = db.Column(db.String(255))
    date = db.Column(db.DateTime(250), default=datetime.utcnow)
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))
    comments = db.relationship('Comments', backref='title', lazy='dynamic')

    def save_pitch(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_pitches(cls,cate):
        pitch = Pitches.query.filter_by(category=cate).all()
        return pitch

    def __repr__(self):
        return f"Pitches {self.pitch}','{self.date}')"
  
class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    author = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    role_id = db.Column(db.Integer,db.ForeignKey('roles.id'))
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pitch = db.relationship('Pitches', backref='author', lazy='dynamic')
    pass_secure = db.Column(db.String(255))
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)
    
    def __repr__(self):
        return f'User {self.author}'
  
class Role(db.Model):
    __tablename__ = 'roles'

    id = db.Column(db.Integer,primary_key = True)
    name = db.Column(db.String(255))
    users = db.relationship('User',backref = 'role',lazy="dynamic")
    

    def __repr__(self):
        return f'User {self.name}'

class Comments(db.Model):
    __tablename__ = 'comments'
    id = db.Column(db.Integer, primary_key=True)
    comment = db.Column(db.String(255))
    date_posted = db.Column(db.DateTime(250), default=datetime.utcnow)
    pitches_id = db.Column(db.Integer, db.ForeignKey("pitches.id"))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))


    def save_comment(self):
        db.session.add(self)
        db.session.commit()

    @classmethod
    def get_comment(cls,id):
        comments = Comments.query.filter_by(pitches_id=id).all()
        return comments

    def __repr__(self):
        return f"Comments('{self.comment}', '{self.date_posted}')"

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField,TextAreaField,SubmitField,SelectField
from wtforms.validators import Required


class PitchForm(FlaskForm):
    title = StringField('Pitch Title')
    category = SelectField(u'Pitch Categories', choices=[('Product', 'Product'), ('Pickup lines', 'Pickup lines'),('Interview', 'Interview')])
    pitch = TextAreaField('Pitch')
    submit = SubmitField('Submit')
    
class CommentForm(FlaskForm):
    comment = TextAreaField('Comment')
    submit = SubmitField('Post Comments')

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [Required()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_uploads import UploadSet,configure_uploads,IMAGES
from flask_mail import Mail
from flask_simplemde import SimpleMDE

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()
photos = UploadSet('photos',IMAGES)
mail = Mail()

simple = SimpleMDE()

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])
    
    # Initializing flask extensions
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    mail.init_app(app)
    simple.init_app(app)


     # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix = '/authenticate')

    
    # configure UploadSet
    configure_uploads(app,photos)

    return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main',__name__)
from . import views,error

def create_app(config_name):
    app = Flask(__name__)

    # Creating the app configurations
    app.config.from_object(config_options[config_name])

    # Initializing flask extensions
    bootstrap.init_app(app)

    # Registering the blueprint
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)

    return app

app/main/views.py
from flask import render_template,request,redirect,url_for,abort
from flask_login import login_required,current_user
from ..models import Pitches,Role,User,Comments
from . import main
from flask import render_template
from .. import db,photos
from .forms import PitchForm,CommentForm,UpdateProfile


@main.route('/')
def index():
    '''
    Index page
    return
    '''
    message= "Welcome to Pitch World!!"
    title= 'Pitch World'
    return render_template('index.html', message=message,title=title)

@main.route('/pitch/', methods = ['GET','POST'])
@login_required
def new_pitch():

    form = PitchForm()

    if form.validate_on_submit():
        category = form.category.data
        pitch= form.pitch.data
        title=form.title.data

        # Updated pitchinstance
        new_pitch = Pitches(title=title,category= category,pitch= pitch,user_id=current_user.id)

        title='New Pitch'

        new_pitch.save_pitch()

        return redirect(url_for('main.index'))

    return render_template('pitch.html',form= form)

@main.route('/categories/<cate>')
def category(cate):
    '''
    function to return the pitches by category
    '''
    category = Pitches.get_pitches(cate)
    # print(category)
    title = f'{cate}'
    return render_template('categories.html',title = title, category = category)

@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(author = uname).first()

    if user is None:
        
        abort(404)

    return render_template("profile/profile.html", user = user)


@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(author = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.author))

    return render_template('profile/update.html',form =form)

@main.route('/user/<uname>/update/pic',methods= ['POST'])
@login_required
def update_pic(uname):
    user = User.query.filter_by(author = uname).first()
    if 'photo' in request.files:
        filename = photos.save(request.files['photo'])
        path = f'photos/{filename}'
        user.profile_pic_path = path
        db.session.commit()
    return redirect(url_for('main.profile',uname=uname))

@main.route('/comments/<id>')
@login_required
def comment(id):
    '''
    function to return the comments
    '''
    comm =Comments.get_comment(id)
    print(comm)
    title = 'comments'
    return render_template('comments.html',comment = comm,title = title)

@main.route('/new_comment/<int:pitches_id>', methods = ['GET', 'POST'])
@login_required
def new_comment(pitches_id):
    pitches = Pitches.query.filter_by(id = pitches_id).first()
    form = CommentForm()

    if form.validate_on_submit():
        comment = form.comment.data

        new_comment = Comments(comment=comment,user_id=current_user.id, pitches_id=pitches_id)

        new_comment.save_comment()

        return redirect(url_for('main.index'))
    title='New Pitch'
    return render_template('new_comment.html',title=title,comment_form = form,pitches_id=pitches_id)

app/templates/base.html
{% extends 'bootstrap/base.html'%}
<!-- Navbar block  -->
{% block navbar %} {% include 'navbar.html' %} {% endblock %}

<head>
    {%block styles %} {{super()}}
    <!--Importing the simple mde css and js files  -->
    {{ simplemde.css}} {{ simplemde.js }}
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css"> {% endblock %}

</head>

app/templates/categories.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index8.css')}}"> {% endblock %} {% block content %}

<body>
    <br>
    <hr>
    <h3 class="text-center">PITCHES</h3>
    <a href="../pitch/"> <button type="button" class="btn btn-success"><i class="fa fa-plus" aria-hidden="true"></i> New Pitch</button></a>
    <br><br>

    <div class="container">
        <div class="row">
            <div class="col-md-3"></div>

            <div class="col-md-6">
                <div class="card-columns">
                    {% for category in category[::-1] %}
                    <div class="card text-center">
                        <div class="card-header">
                            <p><i class="fa fa-user-circle" aria-hidden="true"></i> {{category.author}}</p>
                        </div>
                        <div class="card-body">
                            <h5 class="card-title">{{category.title}}</h5>
                            <p class="card-text"><i class="fas fa-pen-square"></i> {{category.pitch}}</p>
                            <a href="/new_comment/{{category.id}}"> <button type="button" class="btn btn-primary btn-sm">Comment  <i class="fa fa-comment" aria-hidden="true"></i></button> </a>

                            <a href="/comments/{{category.id}}"><button type="button" class="btn btn-primary btn-sm">View comments  <i class="fa fa-comments" aria-hidden="true"></i></button></a> </div>
                        <br>
                        <div class="card-footer text-muted">
                            <i class="fa fa-calendar" aria-hidden="true"></i> {{category.date.strftime('%Y-%m-%d')}}
                        </div>
                    </div>
                    <hr>
                    <br>
                </div>
            </div>
        </div>

        <div class="col-md-3"></div>

        {% endfor %}
    </div>
    </div>
</body>
{% endblock %}

app/templates/comments.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %} {% block content %}

<body>
    <br><br> <br>
    <h3 class="text-center">view new comments </h2>
        {% for comm in comment[::-1] %}
        <div class="container">
            <div class="row">
                <div class="col-md-4"></div>

                <div class="col-md-4">
                    <div class="card-groups">
                        <div class="card">
                            <div class="card-body">
                                <h4 class="card-title">{{comm.author}}</h4>
                                <p class="card-text">{{comm.comment}}.</p>
                            </div>
                            <div class="card-footer bg-transparent border-success"><small>Publish date:{{comm.date_posted.strftime('%Y-%m-%d')}}</small></div>
                        </div>
                    </div>
                </div>

                <div class="col-md-4"></div>
            </div>
        </div>

        {% endfor %}
</body>
{% endblock %}

app/templates/fourOwfour.html
{% extends 'base.html'%} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
</head>

<body>
    <h3>WHOOOPS we can't find that page</h1>
</body>

</html>

app/templates/index.html
{% extends 'base.html'%} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index3.css')}}"> {% endblock %} {% block content %}
<div class="jumbotron" style="margin-top:0;">
    <h2 class="text-center">WELCOME </h2>
    <h2 class="text-center">TO YOUR PITCH YOUR WORLD <i class="fa fa-globe" aria-hidden="true"></i></h2>
    <p class="text-center">In life, you only have 60 seconds to impress someone and say something meaningful.!!!</p>
</div>

<body>

    <div class="container">
        <div class="d-flex justify-content-center row">
            <div class="card-groups">
                <div class="card border-info mb-3 col-md-4">
                    <div class="card-body">
                        <h2 class="card-title">Interview Pitch</h2>
                        <p class="card-text">"A word of advice: your interview is about you. It's not about the school you went to, what you majored in, what your GPA was, or who your parents happen to be or know. Most of that stuff is right on your resume, and it m i even
                            even have gotten you into the room, but it won't get you much farther."</p>
                        <a href="/categories/Interview"><button class="btn btn-primary">View</button></a>
                    </div>
                </div>
                <div class="card border-info mb-3 col-md-4">
                    <div class="card-body">
                        <h2 class="card-title">Pickup lines Pitch</h2>
                        <p class="card-text">"I’m no mathematician, but I’m pretty good with numbers. Tell you what, give me yours and watch what I can do with it."</p>
                        <br>
                        <a href="/categories/Adverts" type="button"><button class="btn btn-primary">View</button></a>
                    </div>
                </div>
                <div class="card border-info mb-3 col-md-4">
                    <div class="card-body ">
                        <h2 class="card-title ">Product Pitch</h2>
                        <p class="card-text ">"There is a saying that if you get something for free, you should know that you 're the product. It was never more true than in the case of Facebook and Gmail and YouTube. You get free social-media services, and you get free funny
                            cat videos. In exchange, you give up the most valuable asset you have, which is your personal data."</p>
                        <a href="/categories/Product"><button class="btn btn-primary">View</button></a>
                    </div>
                </div>



            </div>
        </div>
    </div>
</body>
{% endblock%}

app/templates/macros.html
<!-- Displaying pitches macro -->
{% macro displayPitches(pitch_list) %} {% for pitch in pitch_list %}

<div class="row">

</div>

{% endfor %} {% endmacro %}

app/templates/navbar.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title></title>
</head>

<body>
    <div class="navbar navbar-inverse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/"> PITCH WORLD <i class="fa fa-globe" aria-hidden="true"></i> </a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="/"><i class="fa fa-home" aria-hidden="true"></i> Home</a></li>
                    <li><a href="/categories/Interview">Interview <i class="fa fa-bullseye" aria-hidden="true"></i></a></li>
                    <li><a href="/categories/Adverts">Pickup lines <i class="fa fa-bullseye" aria-hidden="true"></i></a></li>
                    <li><a href="/categories/Product">Product <i class="fa fa-bullseye" aria-hidden="true"></i></a></li>

                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li><a href="../pitch/"><i class="fa fa-plus" aria-hidden="true"></i>  New Pitch</a></li>
                    <li><a href="{{url_for('main.profile',uname=current_user.uname)}}"><i class="fa fa-user" aria-hidden="true"></i>  View Profile</a></li>
                    <li><a href="{{url_for('auth.logout')}}">Log Out  <i class="fas fa-sign-out-alt"></i> </a></li>
                    {% else %}
                    <li><a href="{{url_for('auth.login')}}">Sign in <i class="fas fas fa-sign-in-alt" aria-hidden="true"></i></a></li>
                    {%endif%}
                </ul>
            </div>
        </div>
    </div>
</body>

</html>

app/templates/new_comment.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %} {% block content %}

<body>

    <div class="container">
        <div class="row">
            <br>
            <hr> <br>

            <div class="col-md-3"></div>

            <div class="col-md-6">
                <h3 class="text-center">COMMENT HERE</h3>
                {{ wtf.quick_form(comment_form) }}
            </div>

            <div class="col-md-3"></div>
        </div>

    </div>

</body>

{% endblock %}

app/templates/pitch.html
{% extends 'base.html'%} {% import "bootstrap/wtf.html" as wtf %} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index5.css')}}"> {% endblock %} {% block content %}
<div class="container">
    <div class="row">
        <br>
        <h3 class="text-center"><i class="fa fa-plus" aria-hidden="true"></i> NEW PITCH</h3>
        <hr> <br>
        <div class="col-md-3"></div>

        <div class="col-md-6">
            {{ wtf.quick_form(form) }}
        </div>

        <div class="col-md-3"></div>
    </div>
</div>
{% endblock %}

app/templates/profile/profile.html
{% block content %} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %}
<div class="container">
    <div class="row">
        <!-- displaying  Username-->
        <div class="col-md-4">
            <h3> {{user.username| capitalize}} </h3>

            <!--Displaying user bio-->
            {% if user.bio %}
            <p> {{user.bio}}</p>
            {%else%}
            <p> {{user.username| capitalize}} has no bio </p>
            {% endif %} {% if user == current_user %}
            <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a> {% endif %}
        </div>

        <!--Display profile photo-->
        <div class="col-md-4">
            {% if user.profile_pic_path %}

            <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail"> {%else%}
            <p>No profile picture</p>

            {% endif %} {% if user == current_user %}
            <form action="{{url_for('main.update_pic',uname=user.username)}}" method="post" enctype="multipart/form-data">

                <input type="file" name="photo" class="form-control" required>
                <input type="submit">
            </form>
            {% endif %}
        </div>

    </div>
</div>
{% endblock %}

app/templates/profile/update.html
{% extends 'base.html' %} {% import 'bootstrap/wtf.html' as wtf %} {% block styles%} {{ super() }}
<link rel="stylesheet" href="{{url_for('static',filename='css/index.css')}}"> {% endblock %} {% block content %}

<body>
    <div class="container">
        <div class="row">
            <br> <br>
            <h3 class="text-center">UPDATE PROFILE BIO</h3>
            <br>
            <hr> <br>
            <div class="col-md-4"></div>

            <div class="col-md-4">
                {{wtf.quick_form(form)}}
            </div>

            <div class="col-md-4"></div>
        </div>
    </div>
</body>

{% endblock %}